# Generated by Django 5.2.8 on 2025-11-10 02:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filial', models.CharField(help_text='Nome da filial (ex: PORTO ALEGRE)', max_length=50, verbose_name='Filial')),
                ('produto', models.CharField(help_text='Código do produto (ex: 5053000020)', max_length=20, verbose_name='Produto')),
                ('codigo', models.CharField(help_text='Código curto da conta (ex: FS0920)', max_length=10, verbose_name='Cód.')),
                ('centro_custo', models.CharField(help_text='Código do centro de custo (ex: 2512001)', max_length=10, verbose_name='C. Custo')),
                ('tipo_documento', models.CharField(choices=[('NFS', 'NFS'), ('NF', 'NF'), ('BOLETO', 'Boleto'), ('OUTROS', 'Outros')], default='NFS', help_text='Tipo de documento', max_length=10, verbose_name='Doc.')),
                ('drive', models.CharField(help_text='Origem ou tipo de envio (ex: MUNICIPAL)', max_length=20, verbose_name='Drive')),
                ('fornecedor', models.CharField(help_text='Nome do fornecedor ou razão social', max_length=100, verbose_name='Fornecedor')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da conta fixa', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor')),
                ('grupo', models.CharField(help_text='Código do grupo', max_length=10, verbose_name='Grupo')),
                ('chegada', models.CharField(help_text='Regra de vencimento (ex: Todo dia 5, Dia 10, etc.)', max_length=50, verbose_name='Chegada')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais (ex: quem envia, responsável)', verbose_name='Observações')),
                ('segmento', models.CharField(help_text='Categoria da conta (ex: Assessoria, Aluguel)', max_length=50, verbose_name='Segmento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Conta Fixa',
                'verbose_name_plural': 'Contas Fixas',
                'ordering': ['filial', 'chegada', 'fornecedor'],
                'indexes': [models.Index(fields=['filial'], name='provisao_ib_filial_f637c6_idx'), models.Index(fields=['chegada'], name='provisao_ib_chegada_609805_idx'), models.Index(fields=['segmento'], name='provisao_ib_segment_23e0c0_idx')],
            },
        ),
    ]
