# Generated by Django 5.2.8 on 2025-11-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambiente',
            name='app_name',
            field=models.CharField(blank=True, help_text='Nome do app Django (ex: provisao_ibipora)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ambiente',
            name='url_name',
            field=models.CharField(default='home', help_text='Nome da URL (ex: home)', max_length=100),
        ),
        migrations.AddField(
            model_name='sessaousuario',
            name='ultima_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
